prgrms-be-devcourse/NBE2_2_Team8

- Learner/src/main/java/edu/example/learner/entity/Member.java
> Update_ member 테이블 생성

- Learner/src/main/java/edu/example/learner/entity/Order.java
- Learner/src/main/java/edu/example/learner/entity/OrderStatus.java
> feature order 엔티티 생성

- Learner/src/main/java/edu/example/learner/entity/Member.java
> main code clone

- Learner/src/main/java/edu/example/learner/LearnerApplication.java
- Learner/src/main/java/edu/example/learner/course/dto/NewsResDTO.java
- Learner/src/main/java/edu/example/learner/course/dto/NewsRqDTO.java
- Learner/src/main/java/edu/example/learner/course/entity/Course.java
- Learner/src/main/java/edu/example/learner/course/entity/CourseAttribute.java
- Learner/src/main/java/edu/example/learner/course/entity/NewsEntity.java
- Learner/src/main/java/edu/example/learner/course/entity/Order.java
- Learner/src/main/java/edu/example/learner/course/entity/OrderStatus.java
- Learner/src/main/java/edu/example/learner/course/repository/NewsRepository.java
- Learner/src/main/java/edu/example/learner/course/service/NewsService.java
> Course news

- Learner/src/test/resources/application.properties
> Update 데이터 베이스 연결 설정

- Learner/src/main/java/edu/example/learner/course/dto/CourseDTO.java
- Learner/src/main/java/edu/example/learner/course/dto/OrderDTO.java
- Learner/src/main/java/edu/example/learner/course/dto/OrderItemDTO.java
- Learner/src/main/java/edu/example/learner/course/entity/Course.java
- Learner/src/main/java/edu/example/learner/course/entity/Order.java
- Learner/src/main/java/edu/example/learner/course/entity/OrderItem.java
- Learner/src/main/java/edu/example/learner/course/repository/OrderItemRepository.java
- Learner/src/main/java/edu/example/learner/course/repository/OrderRepository.java
- Learner/src/main/java/edu/example/learner/course/service/OrderServiceImpl.java
- Learner/src/test/java/edu/example/learner/course/repository/CourseRepositoryTests.java
- Learner/src/test/java/edu/example/learner/course/repository/OrderRepositoryTests.java
> -feature & and bugFix OrderCRUD 버그픽스 및 OrderItem 추가 장바구니> 아이템 > 강의 연결

- Learner/src/main/java/edu/example/learner/course/controller/OrderController.java
- Learner/src/main/java/edu/example/learner/course/dto/AlarmDTO.java
- Learner/src/main/java/edu/example/learner/course/entity/TemporaryMember.java
- Learner/src/main/java/edu/example/learner/course/repository/AlarmRepository.java
- Learner/src/main/java/edu/example/learner/course/service/AlarmService.java
- Learner/src/main/java/edu/example/learner/course/service/AlarmServiceImpl.java
- Learner/src/main/java/edu/example/learner/course/service/TemporaryMemberRepository.java
- Learner/src/main/java/edu/example/learner/course/service/TemporaryMemberService.java
- Learner/src/test/java/edu/example/learner/course/service/AlarmServiceImplTest.java
HeartNewsService에서 버그가 하나 있는 것 같습니다
> -bugFix Alarm 버그 제거

- Learner/src/main/java/edu/example/learner/config/JPAAuditConfig.java
- Learner/src/main/java/edu/example/learner/course/service/HeartNewsService.java
> courseAlarm

- Learner/src/main/java/edu/example/learner/config/SecurityConfig.java
- Learner/src/main/java/edu/example/learner/controller/JoinRestController.java
- Learner/src/main/java/edu/example/learner/controller/MemberRestController.java
- Learner/src/main/java/edu/example/learner/controller/advice/APIControllerAdvice.java
- Learner/src/main/java/edu/example/learner/dto/MemberDTO.java
- Learner/src/main/java/edu/example/learner/entity/Order.java
- Learner/src/main/java/edu/example/learner/security/filter/JWTCheckFilter.java
- Learner/src/main/resources/application.properties
> Login 시큐리티 설정 수정 및 Member CRUD 수정

- Learner/src/main/generated/edu/example/learner/courseabout/video/entity/QVideo.java
- Learner/src/main/generated/edu/example/learner/member/entity/QMember.java
- Learner/src/main/java/edu/example/learner/MemberInitializer.java
- Learner/src/main/java/edu/example/learner/alarm/service/AlarmServiceImpl.java
- Learner/src/main/java/edu/example/learner/courseabout/course/entity/Course.java
- Learner/src/main/java/edu/example/learner/courseabout/order/entity/Order.java
- Learner/src/main/java/edu/example/learner/courseabout/order/entity/OrderItem.java
- Learner/src/main/java/edu/example/learner/courseabout/video/VideoInitializer.java
- Learner/src/main/java/edu/example/learner/courseabout/video/entity/Video.java
- Learner/src/main/java/edu/example/learner/member/entity/Member.java
- Learner/src/test/java/edu/example/learner/courseabout/repository/CourseRepositoryTests.java
- Learner/src/test/java/edu/example/learner/courseabout/service/AlarmServiceImplTest.java
- Learner/src/test/java/edu/example/learner/courseabout/service/VideoServiceTest.java
- youtube-time-extractor/src/YoutubePlayer.js
> -BugFix test 버그픽스

- Learner/src/test/java/edu/example/learner/courseabout/service/ReviewServiceTest.java
> Feature ReviewServiceTest 추가

- Learner/learner_react/src/App.js
- Learner/learner_react/src/components/Header.js
- Learner/learner_react/src/components/LoginModal.js
- Learner/learner_react/src/pages/SignUp.js
- Learner/src/main/java/edu/example/learner/config/CorsMvcConfig.java
- Learner/src/main/java/edu/example/learner/member/controller/JoinRestController.java
- Learner/src/main/java/edu/example/learner/member/exception/LoginException.java
- Learner/src/main/java/edu/example/learner/member/exception/MemberException.java
- Learner/src/main/java/edu/example/learner/member/repository/search/MemberSearch.java
- Learner/src/main/java/edu/example/learner/member/repository/search/MemberSearchImpl.java
- Learner/src/main/java/edu/example/learner/member/service/MemberService.java
> Update React 실행 페이지 변경 및 회원가입 완성

- Learner/learner_react/src/pages/CourseNews.js
- Learner/learner_react/src/pages/CourseNewsList.js
- Learner/src/main/java/edu/example/learner/courseabout/news/controller/NewsController.java
> Update 새소식 rest api 수정

- Learner/learner_react/src/pages/Courses.js
- Learner/learner_react/src/pages/OrderCreate.js
- Learner/learner_react/src/pages/OrderDetail.js
- Learner/learner_react/src/pages/Orders.js
- Learner/src/main/java/edu/example/learner/courseabout/course/controller/CourseController.java
- Learner/src/main/java/edu/example/learner/courseabout/order/controller/OrderController.java
- Learner/src/main/java/edu/example/learner/courseabout/video/controller/VideoController.java
- Learner/src/main/resources/application.properties
> -BugFix controller 정리

- .idea/modules/Learner.main.iml
- Learner/learner_react/src/App.js
- Learner/learner_react/src/components/Header.js
- Learner/learner_react/src/pages/OrderCreate.js
- Learner/learner_react/src/pages/OrderDetail.js
- Learner/learner_react/src/pages/OrderUpdate.js
- Learner/learner_react/src/pages/Orders.js
- Learner/src/main/generated/edu/example/learner/courseabout/order/entity/QOrder.java
- Learner/src/main/generated/edu/example/learner/courseabout/order/entity/QOrderItem.java
- Learner/src/main/java/edu/example/learner/alarm/service/AlarmServiceImpl.java
- Learner/src/main/java/edu/example/learner/courseabout/course/entity/Course.java
- Learner/src/main/java/edu/example/learner/courseabout/news/service/HeartNewsService.java
- Learner/src/main/java/edu/example/learner/courseabout/order/controller/OrderController.java
- Learner/src/main/java/edu/example/learner/courseabout/order/dto/OrderDTO.java
- Learner/src/main/java/edu/example/learner/courseabout/order/entity/Order.java
- Learner/src/main/java/edu/example/learner/courseabout/order/repository/OrderItemRepository.java
- Learner/src/main/java/edu/example/learner/courseabout/order/repository/OrderRepository.java
- Learner/src/main/java/edu/example/learner/courseabout/order/service/OrderService.java
- Learner/src/main/java/edu/example/learner/courseabout/order/service/OrderServiceImpl.java
- Learner/src/main/java/edu/example/learner/member/repository/MemberRepository.java
- Learner/src/test/java/edu/example/learner/courseabout/repository/OrderRepositoryTests.java
> -Feature Order수정 및 Order 프론트 페이지

- Learner/learner_react/package-lock.json
- Learner/learner_react/package.json
- Learner/learner_react/src/App.js
- Learner/learner_react/src/pages/CourseNews.js
- Learner/learner_react/src/pages/CourseNewsList.js
- Learner/learner_react/src/pages/CreateNews.js
- Learner/learner_react/src/pages/UpdateNews.js
- Learner/src/main/java/edu/example/learner/courseabout/course/service/CourseServiceImpl.java
- Learner/src/main/java/edu/example/learner/courseabout/news/controller/NewsController.java
- Learner/src/main/java/edu/example/learner/courseabout/news/controller/NewsUtilController.java
- Learner/src/main/java/edu/example/learner/courseabout/news/service/HeartNewsService.java
- Learner/src/main/java/edu/example/learner/member/repository/MemberRepository.java
- Learner/src/main/java/edu/example/learner/member/service/MemberService.java
> React news

- Learner/src/main/java/edu/example/learner/member/service/MemberService.java
> Update MemberService 오류수정

- Learner/learner_react/src/App.js
- Learner/learner_react/src/components/EditProfile.js
- Learner/learner_react/src/components/Header.js
- Learner/learner_react/src/pages/MyPage.js
- Learner/src/main/java/edu/example/learner/courseabout/news/entity/HeartNews.java
- Learner/src/main/java/edu/example/learner/member/controller/MemberRestController.java
- Learner/src/main/java/edu/example/learner/member/exception/MemberException.java
- Learner/src/main/java/edu/example/learner/member/service/MemberService.java
> Update Member CRUD 통합 프론트엔드 호환 완료

- Learner/learner_react/src/App.js
- Learner/learner_react/src/components/Header.js
- Learner/learner_react/src/pages/MyCourses.js
- Learner/src/main/generated/edu/example/learner/courseabout/course/entity/QMemberCourse.java
- Learner/src/main/java/edu/example/learner/courseabout/course/controller/CourseController.java
- Learner/src/main/java/edu/example/learner/courseabout/course/entity/MemberCourse.java
- Learner/src/main/java/edu/example/learner/courseabout/course/repository/MemberCourseRepository.java
- Learner/src/main/java/edu/example/learner/courseabout/course/repository/search/MemberCourseSearch.java
- Learner/src/main/java/edu/example/learner/courseabout/course/service/CourseService.java
- Learner/src/main/java/edu/example/learner/member/entity/Member.java
- Learner/src/main/resources/data.sql
> Update 내 수강 정보 기능 추가

- Learner/learner_react/src/pages/course-review/CourseReview.js
- Learner/learner_react/src/pages/instructor-review/InstructorReview.js
> Update 리뷰 사용자 페이지 추가

- Learner/src/main/generated/edu/example/learner/courseabout/news/entity/QNewsEntity.java
- Learner/src/main/generated/edu/example/learner/member/entity/QMember.java
- Learner/src/main/java/edu/example/learner/courseabout/news/entity/NewsEntity.java
- Learner/src/main/java/edu/example/learner/member/entity/Member.java
> Update: 좋아요 cascade 처리

- Learner/learner_react/src/OrderRoutes.js
- Learner/learner_react/src/YoutubePlayer.js
- Learner/learner_react/src/pages/MyCourses.js
- Learner/learner_react/src/pages/order/OrderCreate.js
- Learner/learner_react/src/pages/order/OrderDelete.js
- Learner/learner_react/src/pages/order/OrderDetail.js
- Learner/learner_react/src/pages/order/OrderUpdate.js
> -BugFix Order 버스 수정

- Learner/learner_react/src/pages/course/CourseCreate.js
- Learner/learner_react/src/pages/course/CourseList.js
- Learner/src/main/java/edu/example/learner/courseabout/course/service/CourseServiceImpl.java
> 강의 생성 부분 오류 수정

- Learner/learner_react/src/pages/order/Orders.js
- Learner/src/main/java/edu/example/learner/courseabout/course/controller/CourseController.java
> -BugFix Order 강의 삭제 시 강의 포함된 주문이 비어있을 경우 주문 삭제 및 장바구니 결제 후 장바구니 삭제 개선

- Learner/learner_react/src/pages/course-review/CourseReviewCreate.js
- Learner/learner_react/src/pages/instructor-review/InstructorReviewCreate.js
- Learner/src/main/java/edu/example/learner/courseabout/coursereview/service/ReviewServiceImpl.java
- Learner/src/main/java/edu/example/learner/courseabout/exception/ReviewException.java
> Review 등록 오류 메시지 수정

- Learner/learner_react/src/pages/course-review/CourseReview.js
- Learner/learner_react/src/pages/instructor-review/InstructorReview.js
- Learner/learner_react/src/pages/instructor-review/InstructorReviewCreate.js
- Learner/learner_react/src/pages/instructor-review/InstructorReviewEdit.js
- Learner/src/main/java/edu/example/learner/courseabout/coursereview/controller/InstructorReviewController.java
- Learner/src/main/java/edu/example/learner/courseabout/coursereview/service/ReviewService.java
- Learner/src/main/java/edu/example/learner/courseabout/coursereview/service/ReviewServiceImpl.java
> Review 등록 오류수정

- Learner/src/main/java/edu/example/learner/courseabout/coursereview/controller/CourseReviewController.java
- Learner/src/main/java/edu/example/learner/courseabout/coursereview/controller/InstructorReviewController.java
- Learner/src/main/java/edu/example/learner/courseabout/coursereview/service/ReviewServiceImpl.java
> Review 스웨거 수정
